fb/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'posts#index'
  get 'posts', to: 'posts#new'
  post 'posts', to: 'posts#create'
  delete 'posts', to: 'posts#destroy'
  get 'user', to: 'users#show'
  get 'users', to: 'users#index'
  post 'comments', to: 'comments#create'
  delete 'comments', to: 'comments#destroy'
  post 'likes_post', to: 'likes#create'
  post 'likes_comment', to: 'likes#create'
  delete 'likes', to: 'likes#destroy'
  post 'friendship', to: 'friendships#create'
  post 'accept_friendship', to: 'friendships#update'
  delete 'cancel_friendship', to: 'friendships#destroy'
  get 'all_requests', to: 'friendships#show'
  get 'post', to: 'posts#show'
  resources :posts, only: %i[create new destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fb/app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  has_many :likes, as: :likeable
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
end

fb/app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_back(fallback_location: root_path)
    else
      @pagy, @posts = pagy_array(Post.all.sort_by(&:created_at).reverse)
      redirect_to root_path
    end
  end

  def destroy
    @comment = Comment.find_by_id(params[:format])
    if @comment && current_user.id == @comment.user_id
      redirect_back(fallback_location: root_path) if @comment.destroy
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

fb/app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def max1(post)
    post.comments.sort_by(&:created_at).reverse[0, 1]
  end

  def all_comments(post)
    post.comments.sort_by(&:created_at).reverse
  end
end

fb/app/views/comments/_comment.html.erb
<div id="comment-<%= comment.id %>" class='comment'>
  <span class="img"><%= profile_img_for comment.user %></span>
  <%= link_to comment.user.user_name, user_path(comment.user), class: :user %>
  <%= content_tag(:div, comment.content, class: :content) %>
  <% if comment.likes.find_by(user_id: current_user.id) %>
    <%= link_to fa_icon("heart", class: "far unheart"), likes_comment_path(:comment_id => comment.id), method: :post, class: "like-link" %>
  <% else %>
    <%= link_to fa_icon("heart", class: "far heart"), likes_comment_path(:comment_id => comment.id), method: :post, class: "like-link" %>
  <% end %>
  <div class="comment-updates">
    <% if current_user == comment.user %>
      <%= link_to "Delete", comments_path(comment), method: :delete %>
    <% end %>
    <% if comment.likes.count > 1 %>
      <span><%= comment.likes.count%> likes</span>
    <% elsif comment.likes.count == 1 %>
      <span><%= comment.likes.count%> like</span>
    <% end %>
  </div>
</div>

fb/app/views/comments/_form.html.erb
<%= form_for Comment.new do |f| %>
  <%= f.hidden_field :post_id, :value => @post.id %>
  <%= content_tag(:span, profile_img_for(current_user), class: "img") %>
  <%= render "error_messages", object: f.object %>
  <%= f.text_field :content, size: "10x5", class: "form-control", placeholder: "Write your comment"%>
  <%= f.submit "Submit" %>
<% end %>