fb/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'posts#index'
  get 'posts', to: 'posts#new'
  post 'posts', to: 'posts#create'
  delete 'posts', to: 'posts#destroy'
  get 'user', to: 'users#show'
  get 'users', to: 'users#index'
  post 'comments', to: 'comments#create'
  delete 'comments', to: 'comments#destroy'
  post 'likes_post', to: 'likes#create'
  post 'likes_comment', to: 'likes#create'
  delete 'likes', to: 'likes#destroy'
  post 'friendship', to: 'friendships#create'
  post 'accept_friendship', to: 'friendships#update'
  delete 'cancel_friendship', to: 'friendships#destroy'
  get 'all_requests', to: 'friendships#show'
  get 'post', to: 'posts#show'
  resources :posts, only: %i[create new destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fb/app/views/layouts/_footer.html.erb
<footer>
  <p> <i>Project by Simon Wathigo @2019.inc</i> </p>
</footer>

fb/app/views/layouts/_header.html.erb
<% @user = current_user %>
<header class="navbar">
  <div class="container">
    <input id="togg" class="togg" type="checkbox">
    <%= link_to "Latest posts", root_path, class: "color-white logo",
        id: "logo" %>
    <% if user_signed_in? %>
    <span welcome>Welcome!  <%= @user.user_name%></span>

    <span class='lg-nav'>
      <span class='lg-nav-profile'><%= image_tag gravatar_image_url(current_user.email) %>
        <%= link_to "My profile", user_path(current_user), class: :name %>
      </span>

      <span onclick="toggleNotification1()" notify>
        <%= fa_icon("bell", class: "fas") %>
        <% if request.env['PATH_INFO'] != all_requests_path %>
          <% if friend_request.size > 0 %>
            <%= fa_icon("caret-down", class: "fas", id: "down1") %>
            <%= fa_icon("caret-up", class: "fas", id: "up1") %>
            <span note2></span>
          <% end %>
      </span>

        <% if friend_request.any? %>
          <div class="note-container">
          <%= render 'notification_list', friendships: friend_request %>
        </div>
        <% end %>
      <% end %>

      <%= link_to "Find friends", users_path, method: :get, class: 'find-friends' %>

      <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'log-out' %>

    </span>
     <label class="fl-right toggle-lable" for="togg"> &#8801;</label>
     <label class="fl-right toggle-lable1" for="togg">&#10006;</label>
     <% if friend_request.size > 0 && request.env['PATH_INFO'] != all_requests_path %>
      <span note></span>
     <% end %>
    <ul class="res-nav">
        <li>
          <div nav-image>
            <span><%= image_tag gravatar_image_url(current_user.email) %>
              <%= link_to "My profile", user_path(current_user), class: :name %>
            </span>
          </div>
        </li>
        <hr>
        <li>
          <%= fa_icon("plus", class: "fas") %>
          <%= link_to "Create Post", posts_path, method: :get %>
        </li>
        <hr>
        <li>
          <%= fa_icon("users", class: "fas") %>
          <%= link_to "Find friends", users_path, method: :get %>
        </li>
        <hr>
        <li>
          <span onclick="toggleNotification()" notify>
          <%= fa_icon("flag-checkered", class: "fas") %>
          <%= link_to "Notifications", "#"%>
          <% if request.env['PATH_INFO'] != all_requests_path %>
            <% if friend_request.size > 0 %>
              <%= fa_icon("caret-down", class: "fas", id: "down") %>
              <%= fa_icon("caret-up", class: "fas", id: "up") %></span>
              <span note1><%= friend_request.size %></span>
            <% end %>
            <% if friend_request.any? %>
            <div class="notification-container">
              <%= render 'notification_list', friendships: friend_request %>
            </div>
            <% end %>
          <% end %>
        </li>
        <hr>
        <li>
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </li>
    <% end %>
    </ul>
  </div>
</header>

fb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Facebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Yrsa&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body onload="rememberState()">
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>