fb/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'posts#index'
  get 'posts', to: 'posts#new'
  post 'posts', to: 'posts#create'
  delete 'posts', to: 'posts#destroy'
  get 'user', to: 'users#show'
  get 'users', to: 'users#index'
  post 'comments', to: 'comments#create'
  delete 'comments', to: 'comments#destroy'
  post 'likes_post', to: 'likes#create'
  post 'likes_comment', to: 'likes#create'
  delete 'likes', to: 'likes#destroy'
  post 'friendship', to: 'friendships#create'
  post 'accept_friendship', to: 'friendships#update'
  delete 'cancel_friendship', to: 'friendships#destroy'
  get 'all_requests', to: 'friendships#show'
  get 'post', to: 'posts#show'
  resources :posts, only: %i[create new destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fb/app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :likes, as: :likeable
  has_many :comments, dependent: :destroy
  validates :content, presence: true
end

fb/app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!

  def new
    @post = current_user.created_posts.build
  end

  def create
    @post = current_user.created_posts.build(post_params)
    if @post.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def index
    @pagy, @posts = pagy_array(timeline_posts.sort_by(&:created_at).reverse)
  end

  def destroy
    @post = Post.find_by_id(params[:format])
    if @post.creator == current_user
      redirect_back(fallback_location: root_path) if @post.destroy
    end
  end

  def show
    @post = @post = Post.find_by_id(params[:format])
  end

  private

  def post_params
    params.require(:post).permit(:content)
  end
end

fb/app/views/posts/_form.html.erb
<%= form_for (Post.new) do |f| %>
  <%= render "error_messages", object: f.object %>

  <%= f.label :content %>
  <%= f.text_area :content, size: "10x5", class: "form-control" %>

  <%= f.submit "Create Post" %>
<% end %>

fb/app/views/posts/_post.html.erb
<% @post = post %>
<% if @post %>
  <li class="post card" id="post-<%= @post.id %>">
    <div class="card-body zoom">
      <div class="creator a-white">
        <span image><%= profile_img_for(post.creator) %></span>
        <span><%= link_to @post.creator.user_name, user_path(post.creator), class: :name %></span>
        <span class="profile-btn"><%= link_to 'View Profile', user_path(post.creator), class: :name %></span>
      </div>
      <a href="/post.<%= @post.id %>" post>
        <span class="content">
          Content: <%= @post.content %>
        </span>
        <span class="timestamp">
          <small>Created <%= time_ago_in_words(@post.created_at) %> ago.</small>
        </span>
      </a>
      <% if (current_user == post.creator) && (request.env['PATH_INFO'] == user_path(current_user)) %>
        <%= link_to 'Delete post', posts_path(@post), method: :delete, class: "delete"%>
      <% end %>
      <hr>
      <input type="checkbox" class="toggle" id="toggle-<%=@post.id%>" checked>
      <ul icons>
        <li>
          <% if @post.likes.find_by(user_id: current_user.id) %>
            <%= link_to fa_icon("heart", class: "far unheart"), likes_post_path(:post_id => @post.id), method: :post, class: "like-link" %>
          <% else %>
            <%= link_to fa_icon("heart", class: "far heart"), likes_post_path(:post_id => @post.id), method: :post, class: "like-link" %>
          <% end %>
        </li>
        <li>
          <label for="toggle-<%=@post.id %>"><%= fa_icon "comment", class: "far comm" %></label>
        </li>
        <% if @post.likes.count > 1 %>
          <span><%= @post.likes.count%> likes</span>
        <% elsif @post.likes.count == 1 %>
          <span><%= @post.likes.count%> like</span>
        <% end %>
      </ul>
      <div class="comments-div">
        <hr>
        <%= render 'comments/form'%>
        <hr>
        <%= render 'comments_list' %>
      </div>
    <div>
  </li>
<% end %>

fb/app/views/posts/index.html.erb
<% @creator ||= current_user %>
<div class="l-container">
  <% if @posts.any? %>
    <div class="post-header">Latest Posts</div>
    <%= render 'posts_list', posts: @posts %>
    <button onclick="toggleNewPost()" class='toggle-post' type="button" name="button">New Post</button>
    <div class="form-overlay">
      <span onclick="closePostForm()" class="close-post">&#10006;</span>
      <div class="post-form-cont">
        <h3>Create a new Post</h3>
        <%= render 'form', creator: @creator %>
      </div>
    </div>
    <% else %>
     <p empty> <b>You don't have any posts, please create one and add some friends</b> </p>
  <% end %>
</div>

fb/app/views/posts/new.html.erb
<% @creator ||= current_user %>
<div class="p-container">
  <div class="new-post">
    <h1>New Post</h1>
    <%= render 'form', creator: @creator %>
  </div>
</div>

fb/app/views/posts/show.html.erb
<div class="post-container">
  <% post = @post %>
  <%= render post %>
</div>