fb/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'posts#index'
  get 'posts', to: 'posts#new'
  post 'posts', to: 'posts#create'
  delete 'posts', to: 'posts#destroy'
  get 'user', to: 'users#show'
  get 'users', to: 'users#index'
  post 'comments', to: 'comments#create'
  delete 'comments', to: 'comments#destroy'
  post 'likes_post', to: 'likes#create'
  post 'likes_comment', to: 'likes#create'
  delete 'likes', to: 'likes#destroy'
  post 'friendship', to: 'friendships#create'
  post 'accept_friendship', to: 'friendships#update'
  delete 'cancel_friendship', to: 'friendships#destroy'
  get 'all_requests', to: 'friendships#show'
  get 'post', to: 'posts#show'
  resources :posts, only: %i[create new destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

fb/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :created_posts, class_name: 'Post',
                           foreign_key: 'creator_id',
                           dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar
  has_many :friendships
  has_many :inverse_friendships, -> { where(confirmed: true) }, class_name: 'Friendship', foreign_key: :friend_id, dependent: :destroy
  has_many :confirmed_friendships, -> { where(confirmed: true) }, class_name: 'Friendship', foreign_key: :user_id, dependent: :destroy
  has_many :confirmed_friends, through: :confirmed_friendships, source: :friend
  has_many :confirmed_inverse_friends, through: :inverse_friendships, source: :user
  has_many :pending_friendships, -> { where(confirmed: false) }, class_name: 'Friendship', foreign_key: :user_id, dependent: :destroy
  has_many :pending_inverse_friendships, -> { where(confirmed: false) }, class_name: 'Friendship', foreign_key: :friend_id, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates :user_name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX }

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.user_name = auth.info.user_name   
    end
  end

  def friends
    confirmed_friends + confirmed_inverse_friends
  end

  def mutual_friends(user)
    friends_v1 = confirmed_friends & user.confirmed_friends
    friends_v2 = confirmed_inverse_friends & user.confirmed_inverse_friends
    (friends_v1 + friends_v2) - [user]
  end

  def confirm_friend(requester)
    friendship = pending_inverse_friendships.find { |friendship| friendship.user == requester }
    friendship.confirmed = true
    friendship.save!
  end

  def friends?(user)
    friends.include?(user)
  end

  def recommended_friends
    friends = User.all.map { |user| user if (!friends? user) && (mutual_friends(user).size > 1) }.compact
    if friends.size < 10
      ((friends + unknown_users(self)) - [self]) - pending_requests
    else
      (friends - [self]) - pending_requests
    end
  end

  def pending_requests
    pending_inverse_friendships.map(&:user)
  end

  def pending_friends
    pending_friendships.map(&:friend)
  end

  private

  def unknown_users(current_user)
    User.all.map { |user| user if !(current_user.friends? user) && !(current_user.pending_requests.include? user) }.compact
  end
end

fb/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

fb/app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by_id(params[:format])
    @pagy, @posts = pagy_array(@user.created_posts.sort_by(&:created_at).reverse) if @user
  end

  def index
    @users = current_user.recommended_friends
  end
end

fb/app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Returns the profile image for the given user.
  def profile_img_for(user)
    image_tag gravatar_image_url(user.email)
  end
end

fb/app/views/users/_user.html.erb
<% @user = user %>
<% if @user %>
    <span user class="user-" id="user-<%= @user.id %>">
      <div avatar>
        <span image><%= image_tag gravatar_image_url(user.email) %></span>
        <%= link_to user.user_name, user_path(user), class: :name %>
      </div>
      <div userdata>
        <% if pending_friend?(@user) %>
          <%= link_to 'Cancel request', cancel_friendship_path(:id => @user.id), method: :delete, class: 'cancel-friend' %>
        <% elsif current_user.friends? @user %>
          <%= link_to 'Unfollow', cancel_friendship_path(:id => @user.id), method: :delete, class: 'cancel-friend' %>
        <% else %>
          <span class="field add-friend">
            <%= link_to 'Add friend', friendship_path(:id => @user.id), method: :post, class: 'request-friend' %>
          </span>
        <% end %>
      </div>
      <div mutuals>
        <% if mutual_friends(@user).any? %>
          <% if mutual_friends(@user).count == 1 %>
            <span><%= mutual_friends(@user).first.user_name %> is a mutual friend</span>
          <% else %>
            <span><%= mutual_friends(@user).first.user_name %> and <%= mutual_friends(@user).count-1 %> <%= mutual_friends(@user).count-1 == 1 ? "other" : "others"%> are mutuals friends</span>
          <% end %>
        <% end %>
      </div>
    </span>
<% end %>

fb/app/views/users/_user_data.html.erb
<section class="user-info">
  <h6 class="h-title">
    <div class="avatar">
      <%= profile_img_for(@user) %>
    </div>
    <span class="userinfo"><%= ("Name: " + @user.user_name) %> </span>
    <span class="userinfo"><%= ("Email: " + @user.email) %> </span>
    <div mutuals>
      <% if mutual_friends(@user).any? && @user != current_user%>
        <% if mutual_friends(@user).count == 1 %>
          <span><%= mutual_friends(@user).first.user_name %> is a mutual friend</span>
        <% else %>
          <span><%= mutual_friends(@user).first.user_name %> and <%= mutual_friends(@user).count-1 %> <%= mutual_friends(@user).count-1 == 1 ? "other" : "others"%> are mutuals friends</span>
        <% end %>
      <% end %>
      <div class="prof-request">
        <% if @user != current_user && (!current_user.friends? @user)%>
          <% if request?(@user) %>
            <%= link_to 'Accept request', accept_friendship_path(:id => @user.id), method: :post, class: 'accept-request' %>
          <% elsif pending_friend?(@user) %>
            <%= link_to 'Cancel request', cancel_friendship_path(:id => @user.id), method: :delete, class: 'cancel-friend' %>
          <% else %>
            <%= link_to 'Add friend', friendship_path(:id => @user.id), method: :post, class: 'request-friend' %>
          <% end %>
        <% end %>
      </div>
      <div friends><%= @user.friends.count %> friends</div>
    </div>
  </h6>
  <% if (current_user.id == @user.id) %>
    <%= link_to "Edit info", edit_user_registration_path,
      class: "edit" %>
  <% end %>
</section>

fb/app/views/users/index.html.erb
<div class="users-container">
  <% if @users.any? %>
    <div class="post-header">People you may know:</div>
    <%= render 'users_list', users: @users %>
  <% end %>
</div>

fb/app/views/users/show.html.erb
<div class="profile-cont">
  <% if @user %>
    <% provide(:title, @user.user_name) %>
    <% provide(:title, @user.email) %>
    <%= render 'user_data' %>
    <div class="profile-posts">
      <%= render 'posts_list', posts: @posts %>
    </div>
    <div class="cl-right"></div>
  <% end %>
</div>